### ISSUE TITLE
Trusted user CA configuration example wrong

### ISSUE THREAD

**Issue by jukeks** [chef-cookbooks/openssh#108]
### Cookbook version
2.5.0

### Chef-client version
13.4.24

### Platform Details
Ubuntu 16.04 in EC2

### Scenario:
Configure Trusted User CA Keys.

### Steps to Reproduce:
Try to use attribute `node['openssh']['server']['trusted_user_c_a_keys']` to set Trusted User CA Keys as is mentioned in README.md. That is set a public key value there.

### Expected Result:
Public key is used to verify user certificates.

### Actual Result:
```
Chef::Exceptions::ValidationFailed
----------------------------------
Property path must be one of: String!  You passed ["ssh-rsa AAAAB3NzaC1yc..."].

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/openssh/recipes/default.rb:46:in `block in from_file'
  /var/chef/cache/cookbooks/openssh/recipes/default.rb:44:in `from_file'
  /var/chef/cache/cookbooks/privx/recipes/default.rb:34:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/openssh/recipes/default.rb:

 39:    end
 40:  
 41:    node.normal['openssh']['server']['listen_address'] = listen_addresses
 42:  end
 43:  
 44:  template 'sshd_ca_keys_file' do
 45:    source 'ca_keys.erb'
 46>>   path node['openssh']['server']['trusted_user_c_a_keys']
 47:    mode node['openssh']['config_mode']
 48:    owner 'root'
 49:    group node['root_group']
 50:  end
 51:  
 52:  template 'sshd_revoked_keys_file' do
 53:    source 'revoked_keys.erb'
 54:    path node['openssh']['server']['revoked_keys']
 55:    mode node['openssh']['config_mode']

System Info:
------------
chef_version=13.4.24
platform=ubuntu
platform_version=16.04
ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
program_name=chef-client worker: ppid=3277;start=14:02:19;
executable=/opt/chef/bin/chef-client
```

**Comment by jukeks** [comment]
The right property would be `node['openssh']['ca_keys']`.

**Comment by iennae** [comment]
Thanks for reporting and fixing this issue!
